version: '3'
services:
  nginx:
    build:
      context: ../images/nginx
    volumes:
      # Mount the workspace directory, where we clone the projects and assemble our images
      - ./workspace:/tmp/workspace:rw
      # Mount the output directory
      - ./volume-qc:/var/www/quickcommerce:rw
      # Mount nginx config
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "8081:80"
      - "443:443"
  php-fpm:
    build:
      context: ../images/php-fpm
    env_file:
      # Configure database user and shop admin user / pw
      - shop-config.env
    volumes:
      # Mount the workspace directory, where we clone the projects and assemble our images
      - ./workspace:/tmp/workspace:rw
      # Mount the output directory
      - ./volume-qc:/var/www/quickcommerce:rw
    links:
      - maria-db
    # Run the workspace setup script
    command: "bash /tmp/workspace/setup.sh"
  maria-db:
    build:
      context: ../images/maria-db
    env_file:
      - shop-config.env
    # Configure via shop-config.env instead
    #environment:
    #  - MYSQL_DATABASE=quickcommerce
    #  - MYSQL_USER=qc-user
    #  - MYSQL_PASSWORD=v@der!4201986
    #  - MYSQL_ROOT_PASSWORD=v@der!4201986
    #  - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./volume-db:/var/lib/db-data
    #volumes:
    #  - ./database/qcdb-default.sql:/docker-entrypoint-initdb.d/data.sql:rw